[web]
54.241.141.163 ansible_user=ec2-user ansible_ssh_private_key_file=/Users/Lukatoni/myworks/amalitech/TeamProject/deg-cohort-2-community-board-team-4/devops/ansible/communityboard-dev-deployer.pem
